### ISSUE TITLE
incapable d'utiliser les fonctionnalités de l'application

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame-v3#244]
**What happened:**
```
incapable d'utiliser les fonctionnalités de l'application
```

**Version:** 3.0.0-beta (31292)

**Operating system:** Android 11

**Model:** Google Pixel 2 XL

**Memory:** 65% (2.33 GB used out of 3.58 GB)

**Capacity:** 90% (46.8 GB used out of 52 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/46/awesome_logs) 

**Attachments:** 

![screenshot_1606881905382.png](http://buglife.s3.amazonaws.com/report_attachments/f1e09b1d0b7f627761daadd54bd03d2bb050d521/original/screenshot_1606881905382.png?1606882055)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/46

Reported via Buglife

**Comment by AlexandreMarkus** [comment]
I have the same error message since yesterday
