### ISSUE TITLE
erreur constante dans l'application

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame-v3#245]
**What happened:**
```
erreur constante dans l'application
```

**Version:** 3.0.0-beta (31292)

**Operating system:** Android 10

**Model:** OnePlus GM1917

**Memory:** 65% (3.47 GB used out of 5.35 GB)

**Capacity:** 51% (54.3 GB used out of 106 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/47/awesome_logs) 

**Attachments:** 

![screenshot_1606942958851.png](http://buglife.s3.amazonaws.com/report_attachments/32f4579b400fed1e8b831b4ec4582cff92cd07de/original/screenshot_1606942958851.png?1606942991)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/47

Reported via Buglife

**Comment by apomalyn** [comment]
Linked to: #244
