### ISSUE TITLE
il n'est pas possible de voir ni mon horaire ni mes notes

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame-v3#246]
**What happened:**
```
il n'est pas possible de voir ni mon horaire ni mes notes
```

**Version:** 3.0.0-beta (31292)

**Operating system:** Android 11

**Model:** Google Pixel 2 XL

**Memory:** 72% (2.58 GB used out of 3.58 GB)

**Capacity:** 69% (35.8 GB used out of 52 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/48/awesome_logs) 

**Attachments:** 

![screenshot_1606947580151.png](http://buglife.s3.amazonaws.com/report_attachments/33309eebdc28af92b07c9877586e9680aa517c23/original/screenshot_1606947580151.png?1606947675)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/48

Reported via Buglife

**Comment by apomalyn** [comment]
Linked to #244
