### ISSUE TITLE
rien ne s'affiche 

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame-v3#247]
**What happened:**
```
rien ne s'affiche 
```

**Version:** 3.0.0-beta (31292)

**Operating system:** Android 10

**Model:** samsung SM-A705W

**Memory:** 64% (3.46 GB used out of 5.39 GB)

**Capacity:** 43% (47.1 GB used out of 110 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/49/awesome_logs) 

**Attachments:** 

![screenshot_1607020037057.png](http://buglife.s3.amazonaws.com/report_attachments/2ce3bf7de3801ba4ba8b02f2a7b59139e852c199/original/screenshot_1607020037057.png?1607020115)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/49

Reported via Buglife

**Comment by apomalyn** [comment]
Linked to #244
