### ISSUE TITLE
on dirait une erreur pour pas mal tout les call d'API au serveur de l'école ou some shit jsp rien marche cest comme si jetais offline

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame-v3#248]
**What happened:**
```
on dirait une erreur pour pas mal tout les call d'API au serveur de l'école ou some shit jsp rien marche cest comme si jetais offline
```

**Version:** 3.0.0-beta (31292)

**Operating system:** Android 8.0.0

**Model:** LGE LG-H831

**Memory:** 70% (2.6 GB used out of 3.7 GB)

**Capacity:** 86% (19.8 GB used out of 23 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/50/awesome_logs) 

**Attachments:** 

![screenshot_1607060629417.png](http://buglife.s3.amazonaws.com/report_attachments/a022643b9f2e11bc3c5f94f52f31ab6e58cf57ed/original/screenshot_1607060629417.png?1607060772)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/50

Reported via Buglife

**Comment by apomalyn** [comment]
Linked to #244
