### ISSUE TITLE
il n'y a plus rien qui s'affiche depuis au moins une semaine. j'ai essayé de supprimer et de réinstaller.

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame-v3#252]
**What happened:**
```
il n'y a plus rien qui s'affiche depuis au moins une semaine. j'ai essayé de supprimer et de réinstaller.
```

**Version:** 3.0.0-beta (31292)

**Operating system:** Android 10

**Model:** samsung SM-G981W

**Memory:** 56% (5.78 GB used out of 10.3 GB)

**Capacity:** 21% (22.8 GB used out of 108 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/53/awesome_logs) 

**Attachments:** 

![screenshot_1607184672644.png](http://buglife.s3.amazonaws.com/report_attachments/eba27599c0ed8decdbb61554f15981de727830a9/original/screenshot_1607184672644.png?1607184869)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/53

Reported via Buglife

**Comment by apomalyn** [comment]
Closed with #244
